In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/scoringproject/df_sub.csv

You can add the rating of a product to current comments
calculate according to the old rating and
Compare.
Read the 1.df_sub.csv data set.
2. What is the average score of the product?
3. Weighted average score according to date
calculate.
4. According to the values of a, b, c from the previous item
Calculate the weighted score.

**1.df_sub.csv read_csv**

In [2]:
df=pd.read_csv("../input/scoringproject/df_sub.csv")

In [3]:
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A3SBTW3WS4IQSN,B007WTAJTO,NaN,"[0, 0]",No issues.,4.0,Four Stars,1406073600,"07 23, 2014"
1,A18K1ODH1I2MVB,B007WTAJTO,0mie,"[0, 0]","Purchased this for my device, it worked as adv...",5.0,MOAR SPACE!!!,1382659200,"10 25, 2013"
2,A2FII3I2MBMUIA,B007WTAJTO,1K3,"[0, 0]",it works as expected. I should have sprung for...,4.0,nothing to really say....,1356220800,"12 23, 2012"
3,A3H99DFEG68SR,B007WTAJTO,1m2,"[0, 0]",This think has worked out great.Had a diff. br...,5.0,Great buy at this price!!! *** UPDATE,1384992000,"11 21, 2013"
4,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"[0, 0]","Bought it with Retail Packaging, arrived legit...",5.0,best deal around,1373673600,"07 13, 2013"

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      4915 non-null   object
 1   asin            4915 non-null   object
 2   reviewerName    4914 non-null   object
 3   helpful         4915 non-null   object
 4   reviewText      4914 non-null   object
 5   overall         4915 non-null   float64
 6   summary         4915 non-null   object
 7   unixReviewTime  4915 non-null   int64
 8   reviewTime      4915 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 345.7+ KB

In [5]:
df.asin.value_counts()

B007WTAJTO    4915
Name: asin, dtype: int64

**2.AVERAGE PRODUCT PRICE**

In [6]:
avg=df.loc[df["overall"]].mean()

In [7]:
print(avg)

overall           4.983723e+00
unixReviewTime    1.368992e+09
dtype: float64

**3.Weighted average score by date
calculate. **

In [8]:
df["reviewTime"]=pd.to_datetime(df["reviewTime"],dayfirst=True)

In [9]:
current_date=pd.to_datetime("2014-12-08 00:00:00")

In [10]:
df["day_diff"]=(current_date-df["reviewTime"]).dt.days

In [11]:
a=df["day_diff"].quantile(0.25)
b=df["day_diff"].quantile(0.50)
c=df["day_diff"].quantile(0.75)

In [12]:
print(a,b,c)

281.0 431.0 601.0

******4.Calculate the weighted score according to the values of a, b, c from the previous item. .******

In [13]:
df.loc[df["day_diff"] <= a, "overall"].mean() * 28 / 100 + \
df.loc[(df["day_diff"] > a) & (df["day_diff"] <= b), "overall"].mean() * 26 / 100 + \
df.loc[(df["day_diff"] > b) & (df["day_diff"] <= c), "overall"].mean() * 24 / 100 + \
df.loc[(df["day_diff"] > c), "overall"].mean() * 22 / 100

4.595593165128118

In [14]:
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,day_diff
0,A3SBTW3WS4IQSN,B007WTAJTO,NaN,"[0, 0]",No issues.,4.0,Four Stars,1406073600,2014-07-23,138
1,A18K1ODH1I2MVB,B007WTAJTO,0mie,"[0, 0]","Purchased this for my device, it worked as adv...",5.0,MOAR SPACE!!!,1382659200,2013-10-25,409
2,A2FII3I2MBMUIA,B007WTAJTO,1K3,"[0, 0]",it works as expected. I should have sprung for...,4.0,nothing to really say....,1356220800,2012-12-23,715
3,A3H99DFEG68SR,B007WTAJTO,1m2,"[0, 0]",This think has worked out great.Had a diff. br...,5.0,Great buy at this price!!! *** UPDATE,1384992000,2013-11-21,382
4,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"[0, 0]","Bought it with Retail Packaging, arrived legit...",5.0,best deal around,1373673600,2013-07-13,513

top 20 comments to be determined

In [15]:
primary20=df.sort_values(by="reviewTime",ascending=True)[0:20]
primary20["reviewText"]

3974    Couldn't ask for more!  The biggest Micro SD C...
1761    Lighting fast card and very well priced. came ...
2881    The Nexus One is listed as supporting a maximu...
502     64GB for this price is a nice deal, especially...
2382    This item works exactly as advertised!  Those ...
206     Great micro SD card for smartphones or other p...
198     Bought this to add storage to a Sansa Fuze MP3...
662     It was what i expected.Didn't test his real sp...
503     I own several video recording devices (Surveil...
3729    I'm using this 32 GB micro Sandisk Ultra to re...
2837    Bought this to go with my Samsung Tab 2 7.0 ta...
317     If your card gets hot enough to be painful, it...
2722    I plugged this into my Galaxy S3 and the memor...
181     So this product is a large disappointment...bo...
1277    Great item. Runs a lot faster then the cheap o...
4220    Never had a problem with any sd cards prior, a...
4572    Memory card fit my phone just fine.  More memo...
1807    i have a Samsung Galaxy S3 phone and the micro...
1924    I bought this to add additional storage for my...
2522    This is a very fast and reliable microSD card....
Name: reviewText, dtype: object

** will be displayed on the job-Product introduction page
Set the top 20 comments. **
** Derive 3 variables from 1.helpful variable helpful_yes, helpful_no, total_vote **

In [16]:
df.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText',
       'overall', 'summary', 'unixReviewTime', 'reviewTime', 'day_diff'],
      dtype='object')

In [17]:
df["helpful"].head()

0    [0, 0]
1    [0, 0]
2    [0, 0]
3    [0, 0]
4    [0, 0]
Name: helpful, dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      4915 non-null   object
 1   asin            4915 non-null   object
 2   reviewerName    4914 non-null   object
 3   helpful         4915 non-null   object
 4   reviewText      4914 non-null   object
 5   overall         4915 non-null   float64
 6   summary         4915 non-null   object
 7   unixReviewTime  4915 non-null   int64
 8   reviewTime      4915 non-null   datetime64[ns]
 9   day_diff        4915 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 384.1+ KB

In [19]:
helpful_full=df.helpful.str.split(n=None,pat=",",expand=True)

In [20]:
df["total_vote"]=helpful_full[1]

In [21]:
df.total_vote.value_counts()

 0]       4360
 1]        380
 2]         96
 3]         25
 5]         13
 4]         11
 7]          7
 6]          3
 8]          3
 16]         1
 2020]       1
 25]         1
 1694]       1
 13]         1
 21]         1
 495]        1
 68]         1
 139]        1
 118]        1
 1505]       1
 109]        1
 49]         1
 48]         1
 236]        1
 10]         1
 65]         1
Name: total_vote, dtype: int64

In [22]:
df["helpful_yes"]=helpful_full[0]

In [23]:
df.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText',
       'overall', 'summary', 'unixReviewTime', 'reviewTime', 'day_diff',
       'total_vote', 'helpful_yes'],
      dtype='object')

In [24]:
df.helpful_yes=df.helpful_yes.str.replace("["," ")

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.

In [25]:
df.total_vote=df.total_vote.str.replace("]"," ")

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.

In [26]:
df.total_vote=df.total_vote.astype("int")

In [27]:
df.helpful_yes=df.helpful_yes.astype("int")

In [28]:
df["helpful_no"]=df.total_vote-df.helpful_yes

In [29]:
df.helpful_no.value_counts()

0      4674
1       175
2        43
3         7
4         2
6         2
27        2
68        1
8         1
9         1
73        1
77        1
10        1
14        1
110       1
126       1
183       1
Name: helpful_no, dtype: int64

In [30]:
def score_pos_neg_diff(pos,neg):
    return pos-neg

In [31]:
df["score_pos_neg_diff"]=score_pos_neg_diff(df.helpful_yes.sum(),
                   df.helpful_no.sum())

In [32]:
def score_average_rating(pos,neg):
    if pos + neg ==0:
        return 0
    return pos/(pos+neg)

In [33]:
df["score_average_rating"]=score_average_rating(df.helpful_yes.sum(),
                   df.helpful_no.sum())

In [34]:
import scipy.stats as st
import math

In [35]:
def wilson_lower_bound(pos, neg, confidence=0.95):
    """
    Wilson Lower Bound Score hesapla

    - The lower limit of the confidence interval to be calculated for the Bernoulli parameter p is accepted as the WLB score.
    - The score to be calculated is used for product ranking.
    - Note: If the scores are between 1-5, it will be marked as 1-3 down, 4-5 up and made suitable for bernoulli. 

    Parameters
    ----------
    pos: int
        positive comment number
    neg: int
        negative commment number
    confidence: float
        confidence interval

    Returns
    -------
    wilson score: float

    """
    n = pos + neg
    if n == 0:
        return 0
    z = st.norm.ppf(1 - (1 - confidence) / 2)
    phat = 1.0 * pos / n
    return (phat + z * z / (2 * n) - z * math.sqrt((phat * (1 - phat) + z * z / (4 * n)) / n)) / (1 + z * z / n)

In [36]:
df["WilsonLB"]=wilson_lower_bound(df.helpful_yes.sum(),df.helpful_no.sum())

In [37]:
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,day_diff,total_vote,helpful_yes,helpful_no,score_pos_neg_diff,score_average_rating,WilsonLB
0,A3SBTW3WS4IQSN,B007WTAJTO,NaN,"[0, 0]",No issues.,4.0,Four Stars,1406073600,2014-07-23,138,0,0,0,5410,0.861728,0.853718
1,A18K1ODH1I2MVB,B007WTAJTO,0mie,"[0, 0]","Purchased this for my device, it worked as adv...",5.0,MOAR SPACE!!!,1382659200,2013-10-25,409,0,0,0,5410,0.861728,0.853718
2,A2FII3I2MBMUIA,B007WTAJTO,1K3,"[0, 0]",it works as expected. I should have sprung for...,4.0,nothing to really say....,1356220800,2012-12-23,715,0,0,0,5410,0.861728,0.853718
3,A3H99DFEG68SR,B007WTAJTO,1m2,"[0, 0]",This think has worked out great.Had a diff. br...,5.0,Great buy at this price!!! *** UPDATE,1384992000,2013-11-21,382,0,0,0,5410,0.861728,0.853718
4,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"[0, 0]","Bought it with Retail Packaging, arrived legit...",5.0,best deal around,1373673600,2013-07-13,513,0,0,0,5410,0.861728,0.853718

In [38]:
last20=df[df["helpful_yes"]==1].sort_values(by="score_average_rating",ascending=False)[0:20]

In [39]:
last20

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,day_diff,total_vote,helpful_yes,helpful_no,score_pos_neg_diff,score_average_rating,WilsonLB
8,A2CYJO155QP33S,B007WTAJTO,4evryoung,"[1, 1]",Works in a HTC Rezound. Was running short of ...,5.0,Loads of room,1395619200,2014-03-24,259,1,1,0,5410,0.861728,0.853718
3676,AL7WELLY5SAN4,B007WTAJTO,Pride,"[1, 1]",I use mine for my GoPro Black Edition and its ...,5.0,Is as advertised,1360627200,2013-12-02,371,1,1,0,5410,0.861728,0.853718
3308,A3BM7G85F9YSLV,B007WTAJTO,MP,"[1, 3]",Ordered two of these and none works w my Cell ...,1.0,Non Compatible,1395878400,2014-03-27,256,3,1,2,5410,0.861728,0.853718
3289,A10UHQH1YL5Q6B,B007WTAJTO,MONTYHADES,"[1, 1]","awesome little sd card, my phone is 32GB but I...",5.0,for Galaxy Note 3..,1398902400,2014-01-05,337,1,1,0,5410,0.861728,0.853718
3274,A2DIQTZPF26T1L,B007WTAJTO,M. Nichols,"[1, 1]",the card arrived promptly in good condition. i...,5.0,"great price, good value",1364169600,2013-03-25,623,1,1,0,5410,0.861728,0.853718
3243,A2XDLV8U033DZ9,B007WTAJTO,Mister Matt,"[1, 1]",A+ on product and seller- Came as described- s...,5.0,Awesome!,1372118400,2013-06-25,531,1,1,0,5410,0.861728,0.853718
3239,A2ARDVMUGDFED6,B007WTAJTO,MiRSD,"[1, 1]",I purchased this card for use in a Microsoft S...,4.0,"Good, cheap card but slow transfers",1394323200,2014-09-03,96,1,1,0,5410,0.861728,0.853718
3221,A37DVHYBMVIEY7,B007WTAJTO,Mike R.,"[1, 1]","Awesome, just awesome. Great speed also. I use...",5.0,High quality,1391644800,2014-06-02,189,1,1,0,5410,0.861728,0.853718
3198,AI2WD20YMB1TS,B007WTAJTO,Mike Calabrese,"[1, 7]",The docs for my Smart Phone said that this car...,1.0,Check Your Phone Docs Before Ordering a microS...,1385683200,2013-11-29,374,7,1,6,5410,0.861728,0.853718
3168,A4ULETG58QUSC,B007WTAJTO,michael lasky,"[1, 1]",stores a lot of HD pictures and videos. no lon...,5.0,qualitty SD card,1386115200,2013-04-12,605,1,1,0,5410,0.861728,0.853718
3159,A1UJGZQJG6BP9K,B007WTAJTO,Michael,"[1, 1]",I put this in my Nokia Lumia 521 and so far it...,5.0,"No Complaints, Writes Fast Enough",1400803200,2014-05-23,199,1,1,0,5410,0.861728,0.853718
3158,AIUT7GNUUB1A7,B007WTAJTO,Michael,"[1, 1]",I noticed amazon had the 'ultra' version for o...,4.0,"Good price, used for Galaxy Tab 2",1370390400,2013-05-06,581,1,1,0,5410,0.861728,0.853718
3147,A2ARZ39EUUNMZM,B007WTAJTO,Michael E. Deming,"[1, 1]",Plug and Play simplicity. Popped it in and it ...,5.0,SanDisk Ultra 128GB MicroSDXC Class 10 UHS 'Wo...,1403136000,2014-06-19,172,1,1,0,5410,0.861728,0.853718
3145,A2Y3SHHH4AJPM5,B007WTAJTO,Michael D Ford,"[1, 1]",SanDisk Ultra 64 GB microSDXC Class 10 UHS-1 M...,5.0,SanDisk Ultra 64 BG Micro SDXC class 10 UHS-1,1346803200,2012-05-09,943,1,1,0,5410,0.861728,0.853718
3141,A2HTWXHSQEC30B,B007WTAJTO,Michael Ceder,"[1, 1]",It's fast. Works as described. Plenty of space...,5.0,It's fast.,1354147200,2012-11-29,739,1,1,0,5410,0.861728,0.853718
3130,A13Z9NU9AGHOPO,B007WTAJTO,Michael A. Davis,"[1, 1]",Using it in a 10&#34; Android Tablet and have ...,5.0,Works Fine:-),1388361600,2013-12-30,343,1,1,0,5410,0.861728,0.853718
3129,A1H1A0TR1K38SQ,B007WTAJTO,M Huston,"[1, 1]",I have two of these that I am using with a GoP...,5.0,Does What It's Supposed to Do!,1378684800,2013-09-09,455,1,1,0,5410,0.861728,0.853718
3111,A2A9ZF3KYXL5D0,B007WTAJTO,Mercury,"[1, 1]","I got this card only a few months ago, used it...",1.0,"Card failed, now is read-only, won't format or...",1404864000,2014-09-07,92,1,1,0,5410,0.861728,0.853718
3096,A2QDWSTK9AGZ8X,B007WTAJTO,megaloskardia,"[1, 1]",Very satisfied with the speed and the space on...,5.0,GREAT. formatting requires extra steps,1360540800,2013-11-02,401,1,1,0,5410,0.861728,0.853718
3325,A2WH3SN2MODL54,B007WTAJTO,"MR. MAV ""Maverickccs""","[1, 3]",The only reason I give one star is that I cant...,1.0,LOST ALL MY FILES IN MY S3,1398729600,2014-04-29,223,3,1,2,5410,0.861728,0.853718